IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Banner')
BEGIN
    CREATE TABLE [Banner](
        Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
        AltText NVARCHAR(MAX) NOT NULL,
        Field NVARCHAR(MAX) NOT NULL,
        StartDate DATETIME NOT NULL,
        EndDate DATETIME NOT NULL,
        EventId UNIQUEIDENTIFIER NOT NULL,
    )
END

ALTER TABLE [Banner]
ADD FOREIGN KEY (EventId) REFERENCES [Event](Id)
