IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ProviderKPI')
BEGIN
    CREATE TABLE [ProviderKPI](
        Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
        Progress FLOAT NOT NULL,
        CreatedDate DATETIME NOT NULL,
        ProviderId UNIQUEIDENTIFIER NOT NULL,
        LeaderboardId UNIQUEIDENTIFIER NOT NULL
    )
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LeaderBoard')
BEGIN
    CREATE TABLE [LeaderBoard](
        Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
        Name NVARCHAR(455) NOT NULL,
        StartDate DATETIME NOT NULL,
        EndDate DATETIME NOT NULL,
        EventId UNIQUEIDENTIFIER NOT NULL
    )
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Event')
BEGIN
    CREATE TABLE [Event](
        Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
        Title NVARCHAR(455) NOT NULL,
        Description NVARCHAR(MAX),
        StartDate DATETIME NOT NULL,
        EndDate DATETIME NOT NULL,
        IsActive BIT DEFAULT 1
    )
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EventImage')
BEGIN
    CREATE TABLE [EventImage](
        Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
        EventId UNIQUEIDENTIFIER NOT NULL,
        StartDate DATETIME NULL,
        EndDate DATETIME NULL,
        Field NVARCHAR(255) NULL
    )
END

ALTER TABLE [LeaderBoard]
ADD FOREIGN KEY (EventId) REFERENCES [Event](Id)

ALTER TABLE [ProviderKPI]
ADD FOREIGN KEY (LeaderBoardId) REFERENCES [LeaderBoard](Id)

ALTER TABLE [ProviderKPI]
ADD FOREIGN KEY (ProviderId) REFERENCES [VigigUser](Id)

ALTER TABLE [EventImage]
ADD FOREIGN KEY (EventId) REFERENCES [Event](Id)


   
    